"""Check Web API coverage and regenerate the skill's command reference."""

from __future__ import annotations

import argparse
import ast
from collections import Counter
from pathlib import Path

from advisor.cli.catalog import COMMANDS


ROOT = Path(__file__).resolve().parents[2]
REFERENCE = ROOT / "skills/ahunter/references/commands.md"


def coverage_errors(api_path: Path = ROOT / "advisor/web/api.py") -> list[str]:
    routes = {}
    sources = [api_path]
    if api_path == ROOT / "advisor/web/api.py":
        sources.append(ROOT / "advisor/research/lagent_api.py")
        sources.append(ROOT / "advisor/research/experiments/api.py")
    source = "\n".join(path.read_text(encoding="utf-8") for path in sources)
    for node in ast.walk(ast.parse(source)):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            if not (isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Attribute)
                    and decorator.func.attr in {"get", "post", "put", "delete", "patch"}
                    and decorator.args and isinstance(decorator.args[0], ast.Constant)
                    and str(decorator.args[0].value).startswith("/api/")):
                continue
            key = (decorator.func.attr.upper(), decorator.args[0].value)
            routes[key] = {arg.arg for arg in node.args.args if arg.arg != "request" and "{" + arg.arg + "}" not in key[1]}
    mapped = {(c.method, c.path): c for c in COMMANDS}
    errors = []
    for key in sorted(routes.keys() - mapped.keys()):
        errors.append(f"API missing CLI command: {key}")
    for key in sorted(mapped.keys() - routes.keys()):
        errors.append(f"CLI targets missing API: {key}")
    for key in routes.keys() & mapped.keys():
        fields = {field.name for field in mapped[key].query}
        if fields != routes[key]:
            errors.append(f"Query parameters differ for {key}: API={sorted(routes[key])}, CLI={sorted(fields)}")
    for values, label in (([c.command for c in COMMANDS], "command"), ([(c.method, c.path) for c in COMMANDS], "route")):
        for value, count in Counter(values).items():
            if count != 1:
                errors.append(f"Duplicate {label}: {value}")
    return errors


def render_reference() -> str:
    lines = ["# A Hunter CLI command reference", "", "Generated by `python -m advisor.cli.maintenance --write`; do not edit by hand.", "",
             "All commands start with `ahunter`. Global options: `--base-url`, `--timeout`, `--pretty` (accepted before or after subcommands).",
             "`ahunter commands` returns the full machine-readable command and field catalog without contacting the API.", "",
             "Body flags can be replaced with `--json FILE` or `--json -` (stdin). JSON uses wire field names below, not option names. Do not mix JSON input and body flags.",
             "Required path values are positional, in the order shown. Query defaults and bounds are enforced by the API. Repeated filters use repeated flags.", ""]
    for command in COMMANDS:
        positional = "".join(f" <{field}>" for field in command.path_fields)
        lines.extend([f"## `{command.command}{positional}`", "", command.help + ".", "",
                      f"`{command.method} {command.path}` · {'Writes state' if command.method != 'GET' else 'Reads state'}", ""])
        if command.download:
            lines.extend(["Requires `--output PATH`; writes original bytes to a new file and returns path, byte count, SHA-256, and content type. Existing files are never replaced.", ""])
        if command.json_only:
            lines.extend([f"Requires `--json FILE` (or `--json -`), containing a JSON {command.json_only}.", ""])
        for location, fields in (("Query", command.query), ("Body", command.body)):
            if fields:
                lines.extend([f"{location} fields:", "", "| Option | JSON/wire field | Type | Requirement | Meaning |", "|---|---|---|---|---|"])
                for field in fields:
                    option = "JSON only" if location == "Body" and command.json_only else f"`{field.option}`"
                    kind = "array" if field.repeated else ("string (UTF-8 file with flags)" if field.kind == "text-file" else field.kind)
                    lines.append(f"| {option} | `{field.name}` | {kind} | {'Required' if field.required else 'Optional'}{' / repeat flag' if field.repeated and option != 'JSON only' else ''} | {field.help or '—'} |")
                lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    errors = coverage_errors()
    expected = render_reference()
    if args.write and not errors:
        REFERENCE.parent.mkdir(parents=True, exist_ok=True)
        REFERENCE.write_text(expected, encoding="utf-8")
    elif not REFERENCE.is_file() or REFERENCE.read_text(encoding="utf-8") != expected:
        errors.append("Skill command reference is stale; run python -m advisor.cli.maintenance --write")
    for error in errors:
        print(error)
    if not errors:
        print(f"PASS: {len(COMMANDS)} API operations covered; skill command reference is current")
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
